name: .NET 6 C# CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: Restore dependencies
      run: dotnet restore
    - name: Build project
      run: dotnet build --configuration Release
    - name: Test project
      run: dotnet test
    - name: Publish project
      run: dotnet publish --configuration Release .publish/SeleniumScraper
    - name: make zip
      shell: pwsh
      run: Compress-Archive -Path .publish/SeleniumScraper/* -DestinationPath .publish/SeleniumScraper.zip
    - name: Create release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        artifacts: ./publish/SeleniumScraper.zip
