name: .NET 6 publish

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: Restore dependencies
      run: dotnet restore
    - name: Build project
      run: dotnet build --configuration Release
    - name: Test project
      run: dotnet test
    - name: Create release
      uses: actions/create-release@v1
      id: create_release
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.version.outputs.version }}
        draft: false
        prerelease: false
    - name: make zip
      shell: pwsh
      run: Compress-Archive -Path bin/Release/net6.0-windows/* -DestinationPath SeleniumScraper-windows.zip
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path:  SeleniumScraper-windows.zip
        asset_name:  SeleniumScraper-windows.zip
        asset_content_type: application/zip
